<?php

require_once 'Persona.php';
require_once 'IChildren.php';
require_once 'TPalata.php';
class Doctor extends Persona
{
    private $solary;
    private $typeProf;

    use TPalata;

    public function __construct($age, $fio, $solary, $typeProf, $numberPalate)
    {
        parent::__construct($age, $fio);

        if (!empty($solary)){
            $this->solary=$solary;
        }else{
            echo 'Зарплата врача не введена';
            $this->solary=0;
        }
        if (!empty($typeProf)){
            $this->typeProf=$typeProf;
        }else{
            echo 'Тип професии врача не введен';
            $this->typeProf='Не введено';
        }

        $this->setNumberPalate($numberPalate);
        $this->getNumberPalate();
    }

    public function setSolary($solary){
        if (!empty($solary)){
            $this->solary=$solary;
        }else{
            echo 'Зарплата врача не введена';
            $this->solary=0;
        }
    }
    public function setTypeProf($typeProf){
        if (!empty($typeProf)){
            $this->typeProf=$typeProf;
        }else{
            echo 'Тип професии врача не введен';
            $this->typeProf='Не введено';
        }
    }

    public function getSolary(){
        return $this->solary;
    }
    public function getTypeProf(){
        return $this->typeProf;
    }

    public function show()
    {
        return parent::show().'Зарплата - '.$this->getSolary().'<br>Должность - '.$this->typeProf.'<br>Врачи лечит в палате номер - '.$this->getNumberPalate().'<br>'; // TODO: Change the autogenerated stub
    }
}