<?php

require_once 'Persona.php';
require_once 'IChildren.php';
require_once 'Diagnoz.php';
require_once 'TPalata.php';
require_once 'Doctor.php';

class Pacient extends Persona implements IChildren
{
    private $profession;
    private $money;

    use TPalata;

    public function __construct($age, $fio, $profession, $money, $nameDiagnoz, $timeMed, $priceMed, $numberPalate)
    {
        parent::__construct($age, $fio);

        $this->diagnoz= new Diagnoz($nameDiagnoz, $timeMed, $priceMed);

        if (!empty($profession)){
            $this->profession=$profession;
        }else{
            $this->profession='Пусто';
            echo 'Не введена профессия';
        }

        if (!empty($money)){
            $this->money=$money;
        }else{
            $this->money=0;
            echo 'Не введены деньги пациента';
        }

        $this->setNumberPalate($numberPalate);
        $this->getNumberPalate();
    }

    public function setDiagnoz($diagnoz){
        if (!empty($diagnoz)){
            $this->diagnoz=$diagnoz;
        }else{
            $this->diagnoz='Пусто';
            echo 'Не введен диагноз';
        }
    }
    public function setProfession($profession){
        if (!empty($profession)){
            $this->profession=$profession;
        }else{
            $this->profession='Пусто';
            echo 'Не введена профессия';
        }
    }
    public function setMoney($money){
        if (!empty($money)){
            $this->money=$money;
        }else{
            $this->money=0;
            echo 'Не введены деньги пациента';
        }
    }

    public function getDiagnoz(){
        return $this->diagnoz;
    }
    public function getProfession(){
        return $this->profession;
    }
    public function getMoney(){
        return $this->money;
    }

    /*----------------------------------------------------------------------*/
    public function cry($age)
    {
        if ($age<21){
            echo '<br>Ребёнок плачет<br>';
        }
        // TODO: Implement cry() method.
    }
    public function play($age)
    {
        if ($age<21){
            echo '<br>Ребёнок играет<br>';
        }
        // TODO: Implement play() method.
    }

    public function doctorAndPacient($money, $priceMed, $doctor){
        if ($money > $priceMed){
            echo '<br>Пациент будет лечиться здесь у доктора</br>'.$doctor->show();
        }else{
            echo '<br>Пациент умер. Запишем что от короны</br>';
            $new = ($doctor->getSolary())-5000;
            echo $doctor->show();
            echo 'Доктора оштрафовали теперь зп у него - '.$new;
        }
    }

    public function show()
    {
        return parent::show().'Диагноз - '.$this->getDiagnoz()->show().'<br>Профессия - '.$this->getProfession().'<br>Деньги пациента - '.$this->getMoney().'<br>Пациент лечиться в палате - '.$this->getNumberPalate().'<br>'; // TODO: Change the autogenerated stub
    }
}